def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '15.5'
prepare_react_native_project!




install! 'cocoapods', :deterministic_uuids => false

setup_permissions([
  'Camera',
  'Notifications',
  'Calendars'
])

target 'shopyshop' do
  config = use_native_modules!
  
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  pod 'RNCalendarEvents', :path => '../node_modules/react-native-calendar-events'
  pod 'Firebase/Crashlytics'

  post_install do |installer|

    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix for Xcode User Script Sandboxing causing Hermes build errors
    # Disable for main project
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
    
    # Disable for all pod targets
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end

    # Détection du type de machine
    arch = `uname -m`.strip

    # simulator EXCLUDED_ARCHS setting:
    installer.pods_project.build_configurations.each do |config|
      if arch == "x86_64"
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      else 
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      end
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        if arch == "x86_64"
          # Mac Intel
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
          config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
        else
          # Mac Apple Silicon (M1/M2/M3/M4)
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
          config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
      end
    end
  end
end